hydra_one:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  hydra_one_front_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hydra_one_front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  hydra_one_front_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hydra_one_front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  hydra_one_back_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hydra_one_back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  hydra_one_back_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hydra_one_back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

